name: Trigger-Rules-Build
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: write

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'SSWConsulting'
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: SSWConsulting
          repository: SSW.Rules.Tina.Nextjs.POC


      - uses: actions/checkout@v4
        with:
          repository: SSWConsulting/SSW.Rules.Tina.Nextjs.POC
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0

      - name: Find latest release branch
        id: find_branch
        run: |
          echo "branch_name=$(git for-each-ref --format='%(refname:short)' refs/remotes/origin/release | sort -V | tail -n 1 | sed 's|^origin/||')" >> "$GITHUB_OUTPUT"

      - name: Build and deploy Rules
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-and-deploy.yml
          repo: SSWConsulting/SSW.Rules.Tina.Nextjs.POC
          ref: ${{ steps.find_branch.outputs.branch_name }}
          token: ${{ steps.generate-token.outputs.token }}
