name: Trigger-Rules-Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger-event:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'SSWConsulting'
    steps:

      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Run image organization script
        run: |
          echo "Running image organization..."
          node scripts/organize-images.js

      - name: Commit and push changes if needed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: auto-organized images via workflow"
            git push origin HEAD
          fi

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: SSWConsulting
          repositories: SSWConsulting/SSW.Rules.Tina.Nextjs.POC

      - name: Find latest release branch
        id: find_branch
        run: |
          echo "branch_name=$(git ls-remote --heads origin | grep -oe 'refs/heads/release/.*' | sort -V | tail -n 1 | sed 's|refs/heads/||')" >> $GITHUB_OUTPUT          

      - name: Trigger remote build-and-deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-and-deploy.yml
          repo: SSWConsulting/SSW.Rules.Tina.Nextjs.POC
          ref: ${{ steps.find_branch.outputs.branch_name }}
          token: "${{ steps.generate-token.outputs.token }}"
