name: Trigger-Rules-POC-Build

on:
  workflow_dispatch:
  push:
    branches:
      - tina/migration-dev-content

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'SSWConsulting'

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.POC_APP_ID }}
          private-key: ${{ secrets.POC_APP_PRIVATE_KEY }}
          owner: SSWConsulting
          repositories: SSW.Rules.Tina.Nextjs.POC

      - name: Checkout Rules POC repo
        uses: actions/checkout@v4
        with:
          repository: SSWConsulting/SSW.Rules.Tina.Nextjs.POC
          token: "${{ steps.generate-token.outputs.token }}"
          fetch-depth: 0             

      - name: Find latest release branch
        id: find_branch
        run: |
          echo "branch_name=$(git branch -r | grep 'origin/release/' | sed 's|origin/||' | sort -V | tail -n1)" >> $GITHUB_OUTPUT

      - name: Debug print release branch
        run: |
          echo "Branch to deploy: ${{ steps.find_branch.outputs.branch_name }}"


      - name: Trigger Tina POC deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-and-deploy.yml
          repo: SSWConsulting/SSW.Rules.Tina.Nextjs.POC
          ref: ${{ steps.find_branch.outputs.branch_name }}
          token: "${{ steps.generate-token.outputs.token }}"