name: Trigger-Rules-POC-Build

on:
  workflow_dispatch:
  push:
    branches:
      - content_deployment

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'SSWConsulting'

    steps:

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.POC_APP_ID }}
          private-key: ${{ secrets.POC_APP_PRIVATE_KEY }}
          owner: SSWConsulting
          repositories: SSW.Rules.Tina.Nextjs.POC

      - uses: actions/checkout@v4
        with:
          repository: SSWConsulting/SSW.Rules.Tina.Nextjs.POC
          token: ${{ steps.generate-token.outputs.token }}

      - name: Find latest release branch or fallback to main
        id: find_branch
        run: |
          BRANCH=$(git branch -r | grep 'origin/release/' | sed 's|origin/||' | sort -V | tail -n1)
          if [ -z "$BRANCH" ]; then
            BRANCH="main"
          fi
          echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT

      - name: Trigger Tina POC deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-and-deploy.yml
          repo: SSWConsulting/SSW.Rules.Tina.Nextjs.POC
          ref: ${{ steps.find_branch.outputs.branch_name }}
          token: "${{ steps.generate-token.outputs.token }}"
